// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  /**
   * pnpx prisma migrate dev --name init 的时候，需要替换成直连url（5432端口），同时如果不使用超级管理员用户名密码会报错：
   * Error: ERROR: permission denied to terminate process
   * DETAIL: Only roles with privileges of the role whose process is being terminated or with privileges of the "pg_signal_backend" role may terminate this process.
   * 应该是权限问题
   */
  datasource: {
    url: process.env["DATABASE_URL"],

    // url: process.env["DIRECT_URL"],
  },
});
